on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: checkdomain
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: ✈ Configure git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials:
            ${{ secrets.FTP_PASS }}
            ${{ secrets.FTP_USER }}
            ${{ secrets.FTP_HOST }}

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: '/httpdocs/'
          local-dir:
            './dist/'
            './ShareDBServer'
          dangerous-clean-slate: true
          delete: true